// ASiC Handel 2.0.9 — Marktintegration, Betriebsdaten und Begehung↔GBO
(function(){
 const GBO_KEY='asicGboStateV1', LINK_KEY='asicMarketLinksV2';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch(e){return f}};
 const modules=()=>[...(GBO_DATA.generalTopics||[]),...(GBO_DATA.areas||[]),...(GBO_DATA.machines||[])];
 const moduleById=id=>modules().find(m=>m[0]===id)||null;
 const questions=id=>GBO_DATA.questions?.[id]||[];
 function auditItems(){const a=read('begehungState',{}),out=[];((typeof AUDIT_CATEGORIES!=='undefined'&&Array.isArray(AUDIT_CATEGORIES))?AUDIT_CATEGORIES:[]).forEach(c=>(c.items||[]).forEach(q=>{if(a.ratings?.[q.id]==='mangel')out.push({id:q.id,categoryId:c.id,category:c.name,text:q.text,comment:a.comments?.[q.id]||'',measure:(a.measures||[]).find(m=>m.itemId===q.id)})}));return out}
 const CATEGORY_MODULE={brandschutz:'brandschutz',sozialräume:'sozial',erstehilfe:'erstehilfe','co2-kuehleinrichtungen':'co2',kühlhaus:'kuehl',lager:'lager_allg',leergut:'leergutrueck',praktikanten:'unterweisung',arbeitsmedizin:'betriebsarzt',backstation:'back',serviceabteilung:'swk',kassenzone:'kassen',gefahrstoffe:'reinigung',marktleiterbüro:'buero','barrierefreies-wc':'sozial',notfall:'notfall',dokumentation:'org','psychische-belastung':'fuehrung',kundenaufzug:'maschinen',lastenaufzug:'maschinen',fluessiggasflaschen:'gasverkauf',beleuchtung:'beleuchtung'};
 const RULES=[[/flucht-? und rettungs|fluchtweg|rettungsweg|notausgang|notausstieg/i,'flucht'],[/leiter|rolltritt|aufstiegshilfe|elefantenfu/i,'leitern'],[/schwerlastregal|regalsystem|traglastangabe.*regal|anfahrschutz/i,'regale'],[/gabelstapler/i,'stapler'],[/flurförder|hubwagen/i,'ffz'],[/rolltor|schnelllauftor/i,'rolltor'],[/automatiktür/i,'automatiktuer'],[/beleuchtung|lichtstärke|blendung|dunkle bereich/i,'beleuchtung'],[/flüssiggas|gasflasche/i,'gasverkauf'],[/raub|überfall/i,'raub'],[/zahlungsmittel|bargeld|geldbestand/i,'zahlung'],[/kasse|kassenstuhl|kassenbereich|transportband/i,'kassen'],[/haut(schutz|pflege)|feuchtarbeit/i,'hautschutz'],[/gefahrstoff|sicherheitsdatenblatt|trgs 510/i,'reinigung'],[/persönliche schutzausrüstung|\bpsa\b/i,'psa'],[/erste hilfe|verbandkasten|ersthelfer/i,'erstehilfe'],[/brandschutzhelfer|feuerlöscher|wandhydrant|brandschutztür|feuerschutz|brandmelde/i,'brandschutz'],[/verkehrsweg|stolper|ausrutsch|umknick/i,'verkehr'],[/treppe/i,'treppe'],[/rampe/i,'rampe'],[/unterweis/i,'unterweisung'],[/betriebsarzt|arbeitsmedizin|vorsorge/i,'betriebsarzt'],[/notruf|alarm|notfall/i,'notfall'],[/kühlhaus/i,'kuehl'],[/co.?2|r-?744/i,'co2'],[/papierpresse|ballenpresse/i,'dixi'],[/leergut/i,'leergutrueck'],[/backofen|backstation|brotschneide/i,'back'],[/messer/i,'hm']];
 const LOCKED=new Set(['co2-kuehleinrichtungen','kühlhaus','erstehilfe','arbeitsmedizin','gefahrstoffe','fluessiggasflaschen','beleuchtung','psychische-belastung']);
 // Fachlich festgelegte Begehung -> konkrete GBO-Frage. Nur diese Zuordnungen werden automatisch vorgegeben.
 // Bei nicht eindeutig festlegbaren Fällen bleibt die konkrete Frage bewusst leer und muss fachlich ausgewählt werden.
 const QUESTION_MAP={
  '1.1':['psa','PSA-02'],'1.2':['ffz','FFZ-02'],'1.3':['automatiktuer','AUTOMATI-15'],'1.6':['leitern','LT-01'],'1.7':['leitern','LT-02'],'1.8':['hm','HM-01'],'1.9':['verkehr','VW-01'],'1.10':['treppe','TREPPE-01'],'1.11':['org','ORG-04'],'1.13':['rolltor','ROLLTOR-15'],'1.14':['rolltor','ROLLTOR-15'],
  '2.1':['brandschutz','BRA-02'],'2.2':['brandschutz','BRA-02'],'2.3':['brandschutz','BRA-02'],'2.4':['brandschutz','BRA-02'],'2.7':['flucht','FL-05'],'2.9':['flucht','FR-01'],'2.10':['flucht','FL-04'],'2.13':['dixi','DX-12'],'3.4':['pause','PAUSE-01'],
  '4.1':['erstehilfe','EH-03'],'4.2':['erstehilfe','EH-03'],'4.3':['erstehilfe','EH-04'],'4.4':['erstehilfe','EH-02'],'4.5':['erstehilfe','EH-06'],'4.6':['erstehilfe','EH-06'],
  '6.1':['co2','CO2-19'],'6.2':['kuehl','KUEHL-02'],'7.2':['kuehl','KUEHL-02'],
  '8.1':['ffz','FFZ-03'],'8.2':['ffz','FFZ-05'],'8.3':['regale','REG-01'],'8.4':['regale','REG-02'],'8.5':['regale','REG-03'],'8.8':['dixi','DX-19'],'8.9':['dixi','DX-04'],'8.10':['verkehr','VW-01'],
  '9.1':['leergutrueck','LR-04'],'9.5':['psa','PSA-01'],'9.6':['leergutrueck','LGR-03'],
  '10.1':['unterweisung','UW-01'],'10.2':['unterweisung','UW-03'],'10.3':['unterweisung','UW-05'],
  '11.1':['betriebsarzt','BA-03'],'11.2':['betriebsarzt','BA-01'],'11.3':['betriebsarzt','BA-02'],'11.4':['hautschutz','HS-01'],'11.6':['sozial','SOZ-03'],
  '17.1':['sozial','SOZ-15'],'17.2':['sozial','SOZ-16'],'17.3':['sozial','SOZ-17'],'17.4':['sozial','SOZ-18'],'17.5':['sozial','SOZ-19'],
  '18.1':['notfall','NF-01'],'18.2':['notfall','NF-02'],'18.3':['notfall','NF-01'],'18.4':['notfall','NF-01'],
  '19.1':['erstehilfe','EH-04'],'19.3':['brandschutz','BRA-03'],'19.5':['unterweisung','UW-03'],'19.6':['unterweisung','UW-04'],'19.7':['org','ORG-02'],
  '23.1':['gasverkauf','GAS-01'],'23.2':['gasverkauf','GAS-02'],'23.3':['gasverkauf','GAS-02'],'23.4':['gasverkauf','GAS-03'],'23.5':['gasverkauf','GAS-01'],'23.6':['gasverkauf','GAS-04'],'23.7':['gasverkauf','GAS-05'],'23.8':['gasverkauf','GAS-06'],'23.9':['gasverkauf','GAS-05'],'23.10':['gasverkauf','GAS-02'],'23.11':['gasverkauf','GAS-03'],'23.12':['gasverkauf','GAS-03'],'23.13':['gasverkauf','GAS-06'],'23.14':['gasverkauf','GAS-01'],'23.15':['gasverkauf','GAS-06'],'23.16':['gasverkauf','GAS-01'],'23.17':['gasverkauf','GAS-02'],'23.18':['gasverkauf','GAS-07'],'23.19':['gasverkauf','GAS-04'],'23.22':['unterweisung','UW-03'],
  '24.1':['beleuchtung','BEL-01'],'24.2':['beleuchtung','BEL-01'],'24.3':['beleuchtung','BEL-01']
 };

 function suggest(r){if(LOCKED.has(r.categoryId)){const m=moduleById(CATEGORY_MODULE[r.categoryId]);if(m)return m}const text=`${r.category||''} ${r.text||''}`;for(const [rx,id] of RULES)if(rx.test(text)){const m=moduleById(id);if(m)return m}return moduleById(CATEGORY_MODULE[r.categoryId])}
 function links(){return read(LINK_KEY,[])} function saveLinks(v){localStorage.setItem(LINK_KEY,JSON.stringify(v))}
 function options(selected){return '<option value="">GBO-Modul auswählen</option>'+modules().map(m=>`<option value="${esc(m[0])}" ${m[0]===selected?'selected':''}>${esc(m[1])}</option>`).join('')}
 function qOptions(mid,selected){return '<option value="">Konkrete GBO-Frage auswählen</option>'+questions(mid).map(q=>`<option value="${esc(q[0])}" ${q[0]===selected?'selected':''}>${esc(q[0])} · ${esc(q[1])}</option>`).join('')}
 function renderFindings(){const box=document.getElementById('auditFindingsV2');if(!box)return;const rows=auditItems(),ls=links();if(!rows.length){box.innerHTML='<p class="gbo-note">In der aktuell geladenen Begehung sind keine Mängel vorhanden.</p>';return}box.innerHTML=rows.map(r=>{const old=ls.find(x=>x.auditId===r.id),sm=suggest(r),fixed=QUESTION_MAP[r.id],mid=old?.gboModuleId||fixed?.[0]||sm?.[0]||'',qid=old?.gboQuestionId||fixed?.[1]||'',fixedOk=!!(fixed&&questions(fixed[0]).some(q=>q[0]===fixed[1]));return `<div class="gbo-v2-finding" data-audit-row="${esc(r.id)}"><div style="flex:1 1 auto"><b>${esc(r.id)} · ${esc(r.category)}</b><p>${esc(r.text)}</p>${r.comment?`<small>Feststellung: ${esc(r.comment)}</small>`:''}<div class="gbo-v2-map"><select data-map-module="${esc(r.id)}">${options(mid)}</select><select data-map-question="${esc(r.id)}">${qOptions(mid,qid)}</select></div><small>${old?'Vormerkung gespeichert. Die GBO-Bewertung bleibt unverändert.':fixedOk?'Fachlich festgelegte GBO-Zuordnung – bitte vor dem Vormerken kontrollieren.':'Keine eindeutige automatische GBO-Frage festgelegt – fachlich auswählen.'}</small></div><div class="gbo-v2-actions">${old?`<button class="gbo-btn secondary" data-open="${esc(r.id)}">GBO öffnen</button><button class="gbo-btn secondary" data-update="${esc(r.id)}">Ändern</button><button class="gbo-btn secondary" data-unlink="${esc(r.id)}">Lösen</button>`:`<button class="gbo-btn secondary" data-save="${esc(r.id)}">Vormerken</button>`}</div></div>`}).join('');
 box.querySelectorAll('[data-map-module]').forEach(sel=>sel.onchange=()=>{const qsel=box.querySelector(`[data-map-question="${CSS.escape(sel.dataset.mapModule)}"]`);if(qsel)qsel.innerHTML=qOptions(sel.value,'')});
 const save=id=>{const r=rows.find(x=>x.id===id),mSel=box.querySelector(`[data-map-module="${CSS.escape(id)}"]`),qSel=box.querySelector(`[data-map-question="${CSS.escape(id)}"]`);if(!r||!mSel?.value)return alert('Bitte zuerst ein passendes GBO-Modul auswählen.');if(!qSel?.value)return alert('Bitte eine konkrete GBO-Frage auswählen.');const m=moduleById(mSel.value),q=questions(mSel.value).find(x=>x[0]===qSel.value);let v=links().filter(x=>x.auditId!==id);v.push({auditId:r.id,auditCategory:r.category,auditText:r.text,auditComment:r.comment||'',gboModuleId:m[0],gboModule:m[1],gboQuestionId:q[0],gboQuestionTitle:q[1],createdAt:new Date().toISOString(),status:'vorgemerkt',mappingSource:(QUESTION_MAP[id]?'fachlich-festgelegt':'manuell-ausgewählt')});saveLinks(v);renderFindings();decorateQuestions()};
 box.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.save));box.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>save(b.dataset.update));box.querySelectorAll('[data-unlink]').forEach(b=>b.onclick=()=>{if(!confirm('Diese Vormerkung wirklich lösen? Die Begehung und die GBO-Bewertung bleiben erhalten.'))return;saveLinks(links().filter(x=>x.auditId!==b.dataset.unlink));renderFindings();decorateQuestions()});box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openGbo(b.dataset.open));}
 function selectModule(st,id){if((GBO_DATA.generalTopics||[]).some(x=>x[0]===id))st.selectedGeneral[id]=true;else if((GBO_DATA.areas||[]).some(x=>x[0]===id))st.selectedAreas[id]=true;else if((GBO_DATA.machines||[]).some(x=>x[0]===id))st.selectedMachines[id]=true}
 function openGbo(auditId){const l=links().find(x=>x.auditId===auditId);if(!l?.gboQuestionId)return alert('Bitte die Vormerkung zuerst einer konkreten GBO-Frage zuordnen.');const st=read(GBO_KEY,{});st.meta=st.meta||{};st.selectedGeneral=st.selectedGeneral||{};st.selectedAreas=st.selectedAreas||{};st.selectedMachines=st.selectedMachines||{};st.answers=st.answers||{};selectModule(st,l.gboModuleId);localStorage.setItem(GBO_KEY,JSON.stringify(st));location.hash=`gbo-q-${l.gboQuestionId}`;location.reload()}
 function decorateQuestions(){document.querySelectorAll('.gbo-linked-note').forEach(x=>x.remove());for(const l of links()){if(!l.gboQuestionId)continue;const el=document.querySelector(`[data-gbo-question="${CSS.escape(l.gboQuestionId)}"]`);if(!el)continue;const n=document.createElement('div');n.className='gbo-linked-note';n.innerHTML=`<b>Begehungsbefund ${esc(l.auditId)} · ${esc(l.auditCategory||'')}</b>${esc(l.auditText||'')}${l.auditComment?`<br>Feststellung: ${esc(l.auditComment)}`:''}`;el.insertBefore(n,el.querySelector('.gbo-statuses'))}const hash=decodeURIComponent(location.hash||'');if(hash.startsWith('#gbo-q-')){const el=document.getElementById(hash.slice(1));if(el){let p=el.parentElement;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement}setTimeout(()=>el.scrollIntoView({behavior:'smooth',block:'center'}),80)}}}
 function copyMeta(){const a=read('begehungState',{}),ci=a.companyInfo||{};const st=read(GBO_KEY,{});st.meta=st.meta||{};const map={marktnummer:ci.marktnummer,plzOrt:ci.plzOrt,strasse:ci.strasse,date:ci.datum,pruefername:ci.pruefername,marktleitung:ci.marktleitung,teilnehmer:ci.teilnehmer};let count=0;for(const [k,v] of Object.entries(map))if(String(v||'').trim()){st.meta[k]=v;count++}localStorage.setItem(GBO_KEY,JSON.stringify(st));if(!count)return alert('In der aktuell geladenen Begehung sind keine Betriebsdaten zum Übernehmen vorhanden.');location.reload()}
 function resetGbo(){if(!confirm('GBO wirklich zurücksetzen?\n\nGelöscht werden GBO-Auswahl, Bewertungen, Bildbelege, Maßnahmen-/Wirksamkeitsangaben und Begehung↔GBO-Vormerkungen.\n\nDie Begehung und die Server-/NAS-Einstellungen bleiben erhalten.'))return;localStorage.removeItem(GBO_KEY);localStorage.removeItem(LINK_KEY);Promise.resolve(window.GBOPhotos?GBOPhotos.clear():null).catch(()=>{}).then(()=>location.reload())}
 async function saveServer(){try{const r=await ASiCMarket.saveServer();alert('Markt auf Server gespeichert: '+(r.fileName||'OK'))}catch(e){alert('Server-Speichern fehlgeschlagen: '+e.message)}}
 async function loadServer(){try{const files=await ASiCMarket.listServer();if(!files.length)return alert('Keine Sicherungen auf dem Server gefunden.');const names=files.map((f,i)=>`${i+1}. ${f.fileName||f.filename||f.name||f}`).join('\n');const n=Number(prompt('Welche Sicherung laden?\n\n'+names));if(!n||!files[n-1])return;const f=files[n-1],name=f.fileName||f.filename||f.name||f;await ASiCMarket.loadServer(name);location.reload()}catch(e){alert('Server-Laden fehlgeschlagen: '+e.message)}}
 function setupGboTabs(){const tabs=[...document.querySelectorAll('[data-gbo-tab]')],panels=[...document.querySelectorAll('[data-gbo-panel]')];if(!tabs.length)return;const activate=(key,scroll=true)=>{tabs.forEach(b=>{const on=b.dataset.gboTab===key;b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false')});panels.forEach(p=>p.hidden=p.dataset.gboPanel!==key);try{localStorage.setItem('asicGboActiveTabV1',key)}catch(e){}if(scroll){const nav=document.querySelector('.gbo-work-nav');if(nav)nav.scrollIntoView({behavior:'smooth',block:'start'})}};tabs.forEach(b=>b.addEventListener('click',()=>activate(b.dataset.gboTab)));let initial='statistik';try{const saved=localStorage.getItem('asicGboActiveTabV1');if(tabs.some(b=>b.dataset.gboTab===saved))initial=saved}catch(e){}activate(initial,false)}
 document.addEventListener('DOMContentLoaded',()=>{setupGboTabs();document.getElementById('marketSaveBtn')?.addEventListener('click',()=>ASiCMarket.download());document.getElementById('marketNasSaveBtn')?.addEventListener('click',saveServer);document.getElementById('marketNasLoadBtn')?.addEventListener('click',loadServer);document.getElementById('copyAuditMetaBtn')?.addEventListener('click',copyMeta);document.getElementById('resetGboBtn')?.addEventListener('click',resetGbo);renderFindings();decorateQuestions();document.addEventListener('asic:gbo-rendered',decorateQuestions)});
})();
